backbone: resnet18
checkpoint: checkpoints/FCOS_18.ckpt
det_thresh: 0.584
detector: FCOS
extra_blocks: false
model_name: FCOS_18
num_classes: 2
patch_size: 1024
returned_layers:
- 1
- 2
- 3
- 4
weights: IMAGENET1K_V1
