backbone: resnext101_32x8d
checkpoint: /home/ammeling/projects/Bhattacharyya/midog/checkpoints/LitFCOS_all_R101x_1024_midogpp_702010_cosLR_0_epoch74_val_ap_0.92.ckpt
det_thresh: 0.548
detector: FCOS
extra_blocks: false
model_name: FCOS_x101
num_classes: 2
patch_size: 1024
returned_layers:
- 1
- 2
- 3
- 4
weights: IMAGENET1K_V2
